/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_handler_NativeHandler */

#ifndef _Included_com_wind_ndk_handler_NativeHandler
#define _Included_com_wind_ndk_handler_NativeHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_handler_NativeHandler
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_handler_NativeHandler_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ndk_handler_NativeHandler
 * Method:    nativeQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_handler_NativeHandler_nativeQuit
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ndk_handler_NativeHandler
 * Method:    nativeSendMessage
 * Signature: (IIILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_handler_NativeHandler_nativeSendMessage
  (JNIEnv *, jobject, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
